{{- if .Values.mtn_rwanda_connector.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mtn-rw-connector"
  labels:
    org.oneacrefund.project: mtn-rwanda-connector
    org.oneacrefund.app: {{ .Release.Name }}-connector
    org.oneacrefund.instance: {{ .Release.Name }}-connector    
spec:
  replicas: {{ .Values.mtn_rwanda_connector.replicas }}
  selector:
    matchLabels:
      org.oneacrefund.project: mtn-rwanda-connector
      org.oneacrefund.app: {{ .Release.Name }}-connector
      org.oneacrefund.instance: {{ .Release.Name }}-connector
  template:
    metadata:
      labels:
        app: mtn-rw-connector
      annotations:
        # Checksum to restart pods on config updates
        # Filebeat hints to enable log collections
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "true"
    spec:
      containers:
        - name: mtn-rw-connector
          image: "{{ .Values.mtn_rwanda_connector.image }}:{{ .Values.mtn_rwanda_connector.imageTag }}"
          imagePullPolicy: "{{ .Values.mtn_rwanda_connector.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.mtn_rwanda_connector.deployment.resources.limits.memory }}"
              cpu: "{{ .Values.mtn_rwanda_connector.deployment.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.mtn_rwanda_connector.deployment.resources.requests.memory }}"
              cpu: "{{ .Values.mtn_rwanda_connector.deployment.resources.requests.cpu }}"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Values.mtn_rwanda_connector.zeebe_broker_contactpoint }}"
            - name: "TENANTS"
              value: "{{ .Values.mtn_rwanda_connector.tenants }}"
            - name: "MTN_API_TIMEOUT"
              value: "{{ .Values.mtn_rwanda_connector.mtn_api_timeout }}"
            - name: "MTN_MAX_RETRY-_COUNT"
              value: "{{ .Values.mtn_rwanda_connector.mtn_max_retry_count }}"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.mtn_rwanda_connector.spring_profiles_active }}"
            - name: "MTNRW_AUTH_HOST"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_auth_host }}"
            - name: "MTNRW_CLIENT_KEY"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_client_key }}"
            - name: "MTNRW_CLIENT_SECRET"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_client_secret }}"
            - name: "MTNRW_API_HOST"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_api_host }}"
            - name: "MTNRW_ENVIRONMENT"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_environmenT }}"
            - name: "MTNRW_SUBSCRIPTIONKEY"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_subscriptionkey }}"
            - name: "MTNRW_CALLBACK"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_callback }}"
            - name: "CAMEL_SERVER_PORT"
              value: "{{ .Values.mtn_rwanda_connector.camel_server_port }}"
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    org.oneacrefund.project: mtn-rwanda-connector
    org.oneacrefund.project: {{ .Release.Name }}-autosave
    org.oneacrefund.app: {{ .Release.Name }}-autosave

  name: mtn-rw-connector
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    org.oneacrefund.instance: {{ .Release.Name }}-autosave
    org.oneacrefund.project: mtn-rwanda-connector
    org.oneacrefund.app: {{ .Release.Name }}-autosave
  sessionAffinity: None
  type: ClusterIP
{{- end}}
